theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
#cursorcolumn = true
bufferline = "multiple"

true-color = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
